version: "3.4"

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  bot:
    container_name: bot
    image: ghcr.io/instruct-lab/instruct-lab-bot/instruct-lab-gobot:main
    depends_on:
      - redis
    volumes:
      - ./config.yaml:/config.yaml

  worker-test:
    container_name: worker-test
    image: ghcr.io/instruct-lab/instruct-lab-bot/instruct-lab-serve:main
    depends_on:
      - redis
    command: ["/instruct-lab-bot-worker", "--test", "--redis", "redis:6379", "generate", "-g", ""]
