---
- name: Log into GHCR
  community.docker.docker_login:
    registry_url: ghcr.io
    username: instructlab-bot
    password: "{{ github_token }}"
    reauthorize: true

- name: Start the container
  community.docker.docker_container:
    name: instructlab-bot
    image: ghcr.io/instructlab/instructlab-bot/instructlab-gobot:main
    state: started
    pull: always
    env:
      ILBOT_GITHUB_INTEGRATION_ID: "{{ app_id }}"
      ILBOT_GITHUB_APP_PRIVATE_KEY: "{{ private_key }}"
      ILBOT_GITHUB_WEBHOOK_SECRET: "{{ webhook_secret }}"
      ILBOT_WEBHOOK_PROXY_URL: "{{ webhook_proxy_url }}"
      ILBOT_REDIS: "{{ redis_ip }}:6379"
      ILBOT_HTTP_ADDRESS: "127.0.0.1"
      ILBOT_HTTP_PORT: "8080"
      ILBOT_MAINTAINERS: "taxonomy-triagers taxonomy-approvers taxonomy-maintainers labrador-org-maintainers instruct-lab-bot-maintainers"
      ILBOT_REQUIRED_LABELS: "skill knowledge"
