apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: instruct-lab-bot
resources:
  - bot
  - redis
  - worker
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: instruct-lab-bot
